id: P25870492
initial_creation_type: input
source_metadata:
  title: Bodhicitta Series
  language: fr
  description: Texts on the subject of bodhicitta (byang chub sems), which (on the
    relative level, at least) is the compassionate wish to attain enlightenment for
    the sake of all living beings—and has been variously translated into English as
    'thought of enlightenment', 'awakening-mind', 'spirit of awakening', etc.
  volume:
    70dc04ce66384422909ddca3593e1af3:
      title: Advice for Tenzin Jamchen
      parent: Advice
    1882f66a484d4538a7fd990c4d3421cd:
      title: Bodhicitta Aspiration
      parent: Aspirations
    bd12a57272f547f7a4723a7e401d60dc:
      title: Aspiration to Generate Bodhicitta, Utterly Pure and Supreme
      parent: Aspirations
    7c89af59082545378e56b72d81c62b64:
      title: An Extensive Commentary on the Four Immeasurables
      parent: Commentaries
    24fd5caa505a4dffa634a217f12f2bbb:
      title: A Brief Commentary on the Refuge & Bodhichitta Prayer known as Sangyé
        Chö Tsok Ma
      parent: Commentaries
    eb1d2f72619b43abaafe6bef27ad98f4:
      title: An Essential Instruction on Refuge and Bodhichitta
      parent: Commentaries
    4d27c1d4df4a4df7a7ae5742954bb614:
      title: How Our Supreme Teacher Generated Bodhicitta and Other Topics
      parent: History
    b9acef628668479e90903e8f5a4b3271:
      title: Daily Confession (from the Vajrapañjara Tantra)
      parent: Practices
    80b432bf0f624349921d67a106add2ba:
      title: The Ritual of the Bodhisattva Vow According to the Tradition of Patrul
        Rinpoche
      parent: Practices
    9f7e37ab835249d9ba9bd43f682902bc:
      title: Verses of Refuge and Bodhicitta
      parent: Practices
    b04562b9a07e451fa07d23a10e3ea83c:
      title: The Three Noble Principles
      parent: Three Noble Principles
created_at: '2022-03-01T03:03:50.799632'
last_modified_at: '2022-03-01T03:03:50.799634'
